#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.0b1 on Wed Feb  7 01:09:22 2018
#

import wx
import mysql.connector
from random import randint

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook_1 = wx.Notebook(self, wx.ID_ANY)
        self.notebook_1_Ustawienia = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.adresip = wx.TextCtrl(self.notebook_1_Ustawienia, wx.ID_ANY, "192.168.0.122")
        self.port = wx.TextCtrl(self.notebook_1_Ustawienia, wx.ID_ANY, "3306")
        self.nick = wx.TextCtrl(self.notebook_1_Ustawienia, wx.ID_ANY, "Anonim")
        self.start = wx.Button(self.notebook_1_Ustawienia, wx.ID_ANY, "START")
        self.notebook_1_Ranking = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_2 = wx.Notebook(self.notebook_1_Ranking, wx.ID_ANY)
        self.notebook_2_pane_1 = wx.Panel(self.notebook_2, wx.ID_ANY)
        self.notebook_2_miesica = wx.Panel(self.notebook_2, wx.ID_ANY)
        self.notebook_2_wszechczasow = wx.Panel(self.notebook_2, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.Start, self.start)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("oknoMain")
        self.start.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_8 = wx.GridSizer(0, 3, 0, 0)
        grid_sizer_7 = wx.GridSizer(0, 3, 0, 0)
        grid_sizer_6 = wx.GridSizer(0, 3, 0, 0)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_5 = wx.GridSizer(0, 2, 0, 0)
        label_5 = wx.StaticText(self.notebook_1_Ustawienia, wx.ID_ANY, "Adres IP: ", style=wx.ALIGN_RIGHT)
        grid_sizer_5.Add(label_5, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_5.Add(self.adresip, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        label_6 = wx.StaticText(self.notebook_1_Ustawienia, wx.ID_ANY, "Port: ", style=wx.ALIGN_RIGHT)
        grid_sizer_5.Add(label_6, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_5.Add(self.port, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        label_7 = wx.StaticText(self.notebook_1_Ustawienia, wx.ID_ANY, "Pseudonim: ", style=wx.ALIGN_RIGHT)
        grid_sizer_5.Add(label_7, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_5.Add(self.nick, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_3.Add(grid_sizer_5, 3, wx.EXPAND, 0)
        sizer_3.Add(self.start, 1, wx.ALL | wx.EXPAND, 0)
        status = wx.StaticText(self.notebook_1_Ustawienia, wx.ID_ANY, u"STATUS PO\u0141\u0104CZENIA")
        sizer_3.Add(status, 0, wx.ALIGN_BOTTOM | wx.FIXED_MINSIZE, 0)
        self.notebook_1_Ustawienia.SetSizer(sizer_3)
        label_8 = wx.StaticText(self.notebook_2_pane_1, wx.ID_ANY, "1.", style=wx.ALIGN_CENTER | wx.ALIGN_RIGHT)
        label_8.SetFont(wx.Font(25, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_6.Add(label_8, 0, wx.ALIGN_CENTER, 0)
        graczt_1 = wx.StaticText(self.notebook_2_pane_1, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        graczt_1.SetFont(wx.Font(25, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_6.Add(graczt_1, 0, wx.ALIGN_CENTER, 0)
        punktyt_1 = wx.StaticText(self.notebook_2_pane_1, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        punktyt_1.SetFont(wx.Font(25, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_6.Add(punktyt_1, 0, wx.ALIGN_CENTER, 0)
        label_9 = wx.StaticText(self.notebook_2_pane_1, wx.ID_ANY, "2.", style=wx.ALIGN_CENTER)
        label_9.SetFont(wx.Font(22, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_6.Add(label_9, 0, wx.ALIGN_CENTER, 0)
        graczt_2 = wx.StaticText(self.notebook_2_pane_1, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        graczt_2.SetFont(wx.Font(22, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_6.Add(graczt_2, 0, wx.ALIGN_CENTER, 0)
        punktyt_2 = wx.StaticText(self.notebook_2_pane_1, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        punktyt_2.SetFont(wx.Font(22, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_6.Add(punktyt_2, 0, wx.ALIGN_CENTER, 0)
        label_10 = wx.StaticText(self.notebook_2_pane_1, wx.ID_ANY, "3.", style=wx.ALIGN_CENTER)
        label_10.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_6.Add(label_10, 0, wx.ALIGN_CENTER, 0)
        graczt_3 = wx.StaticText(self.notebook_2_pane_1, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        graczt_3.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_6.Add(graczt_3, 0, wx.ALIGN_CENTER, 0)
        punktyt_3 = wx.StaticText(self.notebook_2_pane_1, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        punktyt_3.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_6.Add(punktyt_3, 0, wx.ALIGN_CENTER, 0)
        label_11 = wx.StaticText(self.notebook_2_pane_1, wx.ID_ANY, "4.")
        label_11.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_6.Add(label_11, 0, wx.ALIGN_CENTER, 0)
        graczt_4 = wx.StaticText(self.notebook_2_pane_1, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        graczt_4.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_6.Add(graczt_4, 0, wx.ALIGN_CENTER, 0)
        punktyt_4 = wx.StaticText(self.notebook_2_pane_1, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        punktyt_4.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_6.Add(punktyt_4, 0, wx.ALIGN_CENTER, 0)
        label_12 = wx.StaticText(self.notebook_2_pane_1, wx.ID_ANY, "5.")
        label_12.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_6.Add(label_12, 0, wx.ALIGN_CENTER, 0)
        graczt_5 = wx.StaticText(self.notebook_2_pane_1, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        graczt_5.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_6.Add(graczt_5, 0, wx.ALIGN_CENTER, 0)
        punktyt_5 = wx.StaticText(self.notebook_2_pane_1, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        punktyt_5.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_6.Add(punktyt_5, 0, wx.ALIGN_CENTER, 0)
        self.notebook_2_pane_1.SetSizer(grid_sizer_6)
        label_13 = wx.StaticText(self.notebook_2_miesica, wx.ID_ANY, "1.", style=wx.ALIGN_CENTER | wx.ALIGN_RIGHT)
        label_13.SetFont(wx.Font(25, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_7.Add(label_13, 0, wx.ALIGN_CENTER, 0)
        graczm_1 = wx.StaticText(self.notebook_2_miesica, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        graczm_1.SetFont(wx.Font(25, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_7.Add(graczm_1, 0, wx.ALIGN_CENTER, 0)
        punktym_1 = wx.StaticText(self.notebook_2_miesica, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        punktym_1.SetFont(wx.Font(25, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_7.Add(punktym_1, 0, wx.ALIGN_CENTER, 0)
        label_14 = wx.StaticText(self.notebook_2_miesica, wx.ID_ANY, "2.", style=wx.ALIGN_CENTER)
        label_14.SetFont(wx.Font(22, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_7.Add(label_14, 0, wx.ALIGN_CENTER, 0)
        graczm_2 = wx.StaticText(self.notebook_2_miesica, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        graczm_2.SetFont(wx.Font(22, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_7.Add(graczm_2, 0, wx.ALIGN_CENTER, 0)
        punktym_2 = wx.StaticText(self.notebook_2_miesica, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        punktym_2.SetFont(wx.Font(22, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_7.Add(punktym_2, 0, wx.ALIGN_CENTER, 0)
        label_15 = wx.StaticText(self.notebook_2_miesica, wx.ID_ANY, "3.", style=wx.ALIGN_CENTER)
        label_15.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_7.Add(label_15, 0, wx.ALIGN_CENTER, 0)
        graczm_3 = wx.StaticText(self.notebook_2_miesica, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        graczm_3.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_7.Add(graczm_3, 0, wx.ALIGN_CENTER, 0)
        punktym_3 = wx.StaticText(self.notebook_2_miesica, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        punktym_3.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_7.Add(punktym_3, 0, wx.ALIGN_CENTER, 0)
        label_16 = wx.StaticText(self.notebook_2_miesica, wx.ID_ANY, "4.")
        label_16.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_7.Add(label_16, 0, wx.ALIGN_CENTER, 0)
        graczm_4 = wx.StaticText(self.notebook_2_miesica, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        graczm_4.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_7.Add(graczm_4, 0, wx.ALIGN_CENTER, 0)
        punktym_4 = wx.StaticText(self.notebook_2_miesica, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        punktym_4.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_7.Add(punktym_4, 0, wx.ALIGN_CENTER, 0)
        label_17 = wx.StaticText(self.notebook_2_miesica, wx.ID_ANY, "5.")
        label_17.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_7.Add(label_17, 0, wx.ALIGN_CENTER, 0)
        graczm_5 = wx.StaticText(self.notebook_2_miesica, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        graczm_5.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_7.Add(graczm_5, 0, wx.ALIGN_CENTER, 0)
        punktym_5 = wx.StaticText(self.notebook_2_miesica, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        punktym_5.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_7.Add(punktym_5, 0, wx.ALIGN_CENTER, 0)
        self.notebook_2_miesica.SetSizer(grid_sizer_7)
        label_18 = wx.StaticText(self.notebook_2_wszechczasow, wx.ID_ANY, "1.", style=wx.ALIGN_CENTER | wx.ALIGN_RIGHT)
        label_18.SetFont(wx.Font(25, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_8.Add(label_18, 0, wx.ALIGN_CENTER, 0)
        graczw_1 = wx.StaticText(self.notebook_2_wszechczasow, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        graczw_1.SetFont(wx.Font(25, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_8.Add(graczw_1, 0, wx.ALIGN_CENTER, 0)
        punktyw_1 = wx.StaticText(self.notebook_2_wszechczasow, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        punktyw_1.SetFont(wx.Font(25, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_8.Add(punktyw_1, 0, wx.ALIGN_CENTER, 0)
        label_19 = wx.StaticText(self.notebook_2_wszechczasow, wx.ID_ANY, "2.", style=wx.ALIGN_CENTER)
        label_19.SetFont(wx.Font(22, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_8.Add(label_19, 0, wx.ALIGN_CENTER, 0)
        graczw_2 = wx.StaticText(self.notebook_2_wszechczasow, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        graczw_2.SetFont(wx.Font(22, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_8.Add(graczw_2, 0, wx.ALIGN_CENTER, 0)
        punktyw_2 = wx.StaticText(self.notebook_2_wszechczasow, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        punktyw_2.SetFont(wx.Font(22, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_8.Add(punktyw_2, 0, wx.ALIGN_CENTER, 0)
        label_20 = wx.StaticText(self.notebook_2_wszechczasow, wx.ID_ANY, "3.", style=wx.ALIGN_CENTER)
        label_20.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_8.Add(label_20, 0, wx.ALIGN_CENTER, 0)
        graczw_3 = wx.StaticText(self.notebook_2_wszechczasow, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        graczw_3.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_8.Add(graczw_3, 0, wx.ALIGN_CENTER, 0)
        punktyw_3 = wx.StaticText(self.notebook_2_wszechczasow, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        punktyw_3.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_8.Add(punktyw_3, 0, wx.ALIGN_CENTER, 0)
        label_21 = wx.StaticText(self.notebook_2_wszechczasow, wx.ID_ANY, "4.")
        label_21.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_8.Add(label_21, 0, wx.ALIGN_CENTER, 0)
        graczw_4 = wx.StaticText(self.notebook_2_wszechczasow, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        graczw_4.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_8.Add(graczw_4, 0, wx.ALIGN_CENTER, 0)
        punktyw_4 = wx.StaticText(self.notebook_2_wszechczasow, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        punktyw_4.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_8.Add(punktyw_4, 0, wx.ALIGN_CENTER, 0)
        label_22 = wx.StaticText(self.notebook_2_wszechczasow, wx.ID_ANY, "5.")
        label_22.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_8.Add(label_22, 0, wx.ALIGN_CENTER, 0)
        graczw_5 = wx.StaticText(self.notebook_2_wszechczasow, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        graczw_5.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_8.Add(graczw_5, 0, wx.ALIGN_CENTER, 0)
        punktyw_5 = wx.StaticText(self.notebook_2_wszechczasow, wx.ID_ANY, "---", style=wx.ALIGN_CENTER)
        punktyw_5.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        grid_sizer_8.Add(punktyw_5, 0, wx.ALIGN_CENTER, 0)
        self.notebook_2_wszechczasow.SetSizer(grid_sizer_8)
        self.notebook_2.AddPage(self.notebook_2_pane_1, "tygodnia")
        self.notebook_2.AddPage(self.notebook_2_miesica, u"miesi\u0105ca")
        self.notebook_2.AddPage(self.notebook_2_wszechczasow, "wszech czasow")
        sizer_4.Add(self.notebook_2, 1, wx.EXPAND, 0)
        self.notebook_1_Ranking.SetSizer(sizer_4)
        self.notebook_1.AddPage(self.notebook_1_Ustawienia, "Start")
        self.notebook_1.AddPage(self.notebook_1_Ranking, "Ranking")
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        self.SetSize((544, 427))
        # end wxGlade

    def Start(self, event):  # wxGlade: MyFrame.<event_handler>
        file = open('ustawienia.txt','w')
        file.write(self.adresip.GetValue()+'\n')
        file.write(self.port.GetValue()+'\n')
        file.write(self.nick.GetValue())
        file.close()
        frame1 = MyFrame1(None, wx.ID_ANY, "")
        frame1.Show()
        frame.Hide()
        event.Skip()
        
# end of class MyFrame

class MyFrame1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame1.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.pytanie = wx.StaticText(self, wx.ID_ANY, '', style=wx.ALIGN_CENTER)
        self.punkty = wx.StaticText(self, wx.ID_ANY, '0', style=wx.ALIGN_LEFT)
        self.ukryty = wx.StaticText(self, wx.ID_ANY, '0', style=wx.ALIGN_CENTER)
        self.ukryty.Hide()
        self.odp_a = wx.Button(self, wx.ID_ANY, '')
        self.odp_b = wx.Button(self, wx.ID_ANY, '')
        self.odp_c = wx.Button(self, wx.ID_ANY, '')
        self.odp_d = wx.Button(self, wx.ID_ANY, '')

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.odpowiedz_a, self.odp_a)
        self.Bind(wx.EVT_BUTTON, self.odpowiedz_b, self.odp_b)
        self.Bind(wx.EVT_BUTTON, self.odpowiedz_c, self.odp_c)
        self.Bind(wx.EVT_BUTTON, self.odpowiedz_d, self.odp_d)
        # end wxGlade

        file = open('ustawienia.txt','r')
        adresip = file.readlines(1)
        adresip = adresip[0].strip()
        port = file.readlines(2)
        port = port[0].strip()
        nick = file.readlines(3)
        nick = nick[0].strip()
        file.close()
        global cnx
        global cursor
        cnx = mysql.connector.connect(host=adresip,port=port,user='user',password='', database='ps')
        cursor = cnx.cursor()
        global waznaFunkcja
        def waznaFunkcja(self):
            query = ("SELECT id_pytania FROM pytania ORDER BY id_pytania DESC LIMIT 1")
            cursor.execute(query)
            ilePytan = cursor.fetchall()
            randNum = randint(1, ilePytan[0][0])
            query = ("SELECT * FROM pytania WHERE id_pytania=" + str(randNum))
            cursor.execute(query)
            pytanieBaza = cursor.fetchall()
            pytanieBaza = pytanieBaza[0];
            print (pytanieBaza)
        
            self.pytanie.SetLabel(pytanieBaza[1])
            self.odp_a.SetLabel(pytanieBaza[2])
            self.odp_b.SetLabel(pytanieBaza[3])
            self.odp_c.SetLabel(pytanieBaza[4])
            self.odp_d.SetLabel(pytanieBaza[5])
            self.ukryty.SetLabel(str(pytanieBaza[6]))
        waznaFunkcja(self)
        

    def __set_properties(self):
        # begin wxGlade: MyFrame1.__set_properties
        self.SetTitle("Quiz")
        self.SetBackgroundColour(wx.Colour(255, 255, 255))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame1.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_4 = wx.GridSizer(0, 2, 0, 0)
        grid_sizer_3 = wx.GridSizer(0, 4, 0, 0)
        label_3 = wx.StaticText(self, wx.ID_ANY, "Punkty:", style=wx.ALIGN_RIGHT)
        grid_sizer_3.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_3.Add(self.punkty, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_3.Add((0, 0), 0, 0, 0)
        grid_sizer_3.Add((0, 0), 0, 0, 0)
        sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)
        sizer_2.Add(self.pytanie, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_4.Add(self.odp_a, 0, wx.EXPAND, 0)
        grid_sizer_4.Add(self.odp_b, 0, wx.EXPAND, 0)
        grid_sizer_4.Add(self.odp_c, 0, wx.EXPAND, 0)
        grid_sizer_4.Add(self.odp_d, 0, wx.EXPAND, 0)
        sizer_2.Add(grid_sizer_4, 3, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        self.Layout()
        self.SetSize((441, 318))
        # end wxGlade

    global dodajPunkt
    def dodajPunkt(self):
        intpunkty = int(self.punkty.GetLabel())
        intpunkty += 1
        self.punkty.SetLabel(str(intpunkty))

    global przegrana
    def przegrana(self):
        cursor.close()
        cnx.close()
        self.ukryty.SetLabel('przegrałeś')
        self.ukryty.Show()
        
        

    def odpowiedz_a(self, event):  # wxGlade: MyFrame1.<event_handler>
        wybrana_odpowiedz='1'
        if wybrana_odpowiedz == self.ukryty.GetLabel():
            waznaFunkcja(self)
            dodajPunkt(self)
        else:
            przegrana(self)
        event.Skip()

    def odpowiedz_b(self, event):  # wxGlade: MyFrame1.<event_handler>
        wybrana_odpowiedz='2'
        if wybrana_odpowiedz == self.ukryty.GetLabel():
            waznaFunkcja(self)
            dodajPunkt(self)
        else:
            przegrana(self)
        event.Skip()
    def odpowiedz_c(self, event):  # wxGlade: MyFrame1.<event_handler>
        wybrana_odpowiedz='3'
        if wybrana_odpowiedz == self.ukryty.GetLabel():
            waznaFunkcja(self)
            dodajPunkt(self)
        else:
            przegrana(self)
        event.Skip()
    def odpowiedz_d(self, event):  # wxGlade: MyFrame1.<event_handler>
        wybrana_odpowiedz='4'
        if wybrana_odpowiedz == self.ukryty.GetLabel():
            waznaFunkcja(self)
            dodajPunkt(self)
        else:
            przegrana(self)
        event.Skip()

        

# end of class MyFrame1

if __name__ == "__main__":
    quiz = wx.PySimpleApp()
    frame = MyFrame(None, wx.ID_ANY, "")
    quiz.SetTopWindow(frame)
    frame.Show()
    quiz.MainLoop()
